# Generated by Django 4.1.12 on 2023-10-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
